In [43]:
import pandas as pd
df = pd.read_csv('nba_games20.csv')
df.head()
df = df.drop(df.columns[[6,8]],axis=1)
df.columns = ['date','visitor','visitor_points','host','host_points','BoxScore1','BoxScore']
df = df.drop(df.columns['BoxScore1'],axis=1)


df1 = df[df.iloc[:,4] +  df.iloc[:,2 ] > 240]
df.describe()
df.head()

,date,visitor,visitor_points,host,host_points,BoxScore,OT
0,Tue Oct 17 2017 10:30p,Houston Rockets,122,Golden State Warriors,121,Box Score,19596
1,Wed Oct 18 2017 7:30p,Milwaukee Bucks,108,Boston Celtics,100,Box Score,18624
2,Wed Oct 18 2017 8:30p,Atlanta Hawks,117,Dallas Mavericks,111,Box Score,19709
3,Wed Oct 18 2017 7:00p,Charlotte Hornets,90,Detroit Pistons,102,Box Score,20491
4,Wed Oct 18 2017 7:00p,Brooklyn Nets,131,Indiana Pacers,140,Box Score,15008